package org.example.backend.services;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.example.backend.dtos.BookingResponseDTO;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

@Service
public class PdfGeneratorService {

    private static final Font TITLE_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, Color.DARK_GRAY);
    private static final Font SUBTITLE_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, Color.GRAY);
    private static final Font LABEL_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.BLACK);
    private static final Font VALUE_FONT = FontFactory.getFont(FontFactory.HELVETICA, 12, Color.BLACK);
    private static final Font TABLE_HEADER_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.WHITE);
    private static final Font TABLE_CELL_FONT = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.BLACK);

    public ByteArrayInputStream generateBookingConfirmation(BookingResponseDTO booking, String resourceName) {
        Document document = new Document();
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Header Section
            Paragraph title = new Paragraph("SPRING CAMPUS OPERATIONS", TITLE_FONT);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            Paragraph subtitle = new Paragraph("Official Booking Confirmation", SUBTITLE_FONT);
            subtitle.setAlignment(Element.ALIGN_CENTER);
            subtitle.setSpacingAfter(30);
            document.add(subtitle);

            // Information Table
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10);
            table.setWidths(new int[]{2, 5});

            addTableRow(table, "Booking Registry ID:", booking.getId());
            addTableRow(table, "Resource Allocated:", resourceName);
            addTableRow(table, "Institutional Date:", booking.getStartTime().toLocalDate().toString());
            addTableRow(table, "Temporal Windows:", booking.getStartTime().format(DateTimeFormatter.ofPattern("HH:mm")) + 
                                               " - " + booking.getEndTime().format(DateTimeFormatter.ofPattern("HH:mm")));
            addTableRow(table, "Mission Purpose:", booking.getPurpose());
            addTableRow(table, "Participant Cohort:", String.valueOf(booking.getAttendees()));
            addTableRow(table, "Operational Status:", booking.getStatus().toString());

            document.add(table);

            // Footer / Seal
            Paragraph footer = new Paragraph("\n\nThis is a digitally interrogated institutional record generated by the PAF Authentication Cluster.", 
                                            FontFactory.getFont(FontFactory.HELVETICA, 8, Color.LIGHT_GRAY));
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
        } catch (DocumentException ex) {
            ex.printStackTrace();
        }

        return new ByteArrayInputStream(out.toByteArray());
    }

    public ByteArrayInputStream generateBookingReport(List<BookingResponseDTO> bookings, Map<String, Long> summary) {
        Document document = new Document(PageSize.A4.rotate());
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Header
            Paragraph title = new Paragraph("STRATEGIC BOOKING ANALYTICS REPORT", TITLE_FONT);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            Paragraph datePara = new Paragraph("Generated on: " + java.time.LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")), 
                                             FontFactory.getFont(FontFactory.HELVETICA, 10, Color.GRAY));
            datePara.setAlignment(Element.ALIGN_RIGHT);
            datePara.setSpacingAfter(20);
            document.add(datePara);

            // Summary Info
            Paragraph sumPara = new Paragraph(String.format("Total: %d | Approved: %d | Pending: %d | Rejected: %d", 
                                              summary.get("total"), summary.get("approved"), 
                                              summary.get("pending"), summary.get("rejected")), LABEL_FONT);
            sumPara.setSpacingAfter(15);
            document.add(sumPara);

            // Table
            PdfPTable table = new PdfPTable(7);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{3.5f, 2.5f, 2f, 2f, 4f, 1.5f, 2f});

            String[] headers = {"ID", "User", "Date", "Duration", "Purpose", "Atnd", "Status"};
            for (String header : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(header, TABLE_HEADER_FONT));
                cell.setBackgroundColor(Color.BLACK);
                cell.setPadding(5);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);
            }

            for (BookingResponseDTO b : bookings) {
                table.addCell(createCell(b.getId().substring(0, 8) + "..", TABLE_CELL_FONT));
                table.addCell(createCell(b.getUserId(), TABLE_CELL_FONT));
                table.addCell(createCell(b.getStartTime().toLocalDate().toString(), TABLE_CELL_FONT));
                table.addCell(createCell(b.getStartTime().format(DateTimeFormatter.ofPattern("HH:mm")) + "-" + 
                                         b.getEndTime().format(DateTimeFormatter.ofPattern("HH:mm")), TABLE_CELL_FONT));
                table.addCell(createCell(b.getPurpose(), TABLE_CELL_FONT));
                table.addCell(createCell(String.valueOf(b.getAttendees()), TABLE_CELL_FONT));
                
                PdfPCell statusCell = createCell(b.getStatus().toString(), TABLE_CELL_FONT);
                if (b.getStatus().toString().equals("APPROVED")) statusCell.setBackgroundColor(new Color(230, 255, 230));
                if (b.getStatus().toString().equals("REJECTED")) statusCell.setBackgroundColor(new Color(255, 230, 230));
                table.addCell(statusCell);
            }

            document.add(table);
            document.close();
        } catch (DocumentException ex) {
            ex.printStackTrace();
        }

        return new ByteArrayInputStream(out.toByteArray());
    }

    private void addTableRow(PdfPTable table, String label, String value) {
        PdfPCell cellLabel = new PdfPCell(new Phrase(label, LABEL_FONT));
        cellLabel.setBorder(Rectangle.NO_BORDER);
        cellLabel.setPadding(10);
        table.addCell(cellLabel);

        PdfPCell cellValue = new PdfPCell(new Phrase(value, VALUE_FONT));
        cellValue.setBorder(Rectangle.NO_BORDER);
        cellValue.setPadding(10);
        table.addCell(cellValue);
    }

    private PdfPCell createCell(String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setPadding(5);
        cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        return cell;
    }
}
