spring.application.name=backend
server.port=8089

# Keep your new link exactly the same
spring.mongodb.uri=mongodb+srv://tharu:cYsoTU5i8UCPA7VR@cluster0.rco91hg.mongodb.net/ITPM?appName=Cluster0&tlsAllowInvalidCertificates=true

# Change this to PAF to match your screenshot!
spring.mongodb.database=PAF