spring.application.name=backend
server.port=8087

# The new standard Spring Boot 3+ property names
spring.mongodb.uri=mongodb+srv://fyou35160_db_user:x2BbfESWl6lNZmDI@cluster0.4rfbq6j.mongodb.net/smart-campus-operations-system?appName=Cluster0&tlsAllowInvalidCertificates=true
spring.mongodb.database=smart-campus-operations-system