spring.application.name=backend

spring.mongodb.uri=mongodb+srv://scadmin:scadmin123@smart-campus.x9uddwk.mongodb.net/smart_campus_db?retryWrites=true&w=majority&appName=smart-campus

server.port=8080

jwt.secret=smartcampus2026supersecretkey1234567890abcdef
jwt.expiration=86400000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=672358157237-corbqd34267gd28tt1ptuvg5q8qfb5n0.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google